apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: MYSECRET
  namespace: MYNAMESPACE
data:
  # The value of this key is a base64 of the "real" value.
  AWS_DEFAULT_REGION: "dXMtZWFzdC0xCg=="

# 
# This file should NEVER be committed to code with a real secret in it!!
# DO NOT COMMIT THIS FILE
# 
# Instead, use this file with kubeseal to generate your sealed-secret, which
# should be put under source control.
# 
