apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: SOME-nfs-pvc
  namespace: MYNAMESPACE
spec:
  storageClassName: MYAPP-sc
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi


# 
# PVCS can map to remote NFS shares, to local cluster storage, to Longhorn volumes, and other
# persistent storage. The capacity as defined (10G in this example) can be enlarged but never
# shrunken. See https://kubernetes.io/docs/concepts/storage/persistent-volumes/
#
# Possible values for accessModes are: 
# 
#   ReadWriteOnce - the volume can be mounted as read-write by a single node. ReadWriteOnce access mode still can allow multiple pods to access the volume when the pods are running on the same node.
#
#   ReadOnlyMany - the volume can be mounted as read-only by many nodes.
# 
#   ReadWriteMany - the volume can be mounted as read-write by many nodes.
# 
#   ReadWriteOncePod - the volume can be mounted as read-write by a single Pod. Use ReadWriteOncePod access mode if you want to ensure that only one pod across whole cluster can read that PVC or write to it. This is only supported for CSI volumes and Kubernetes version 1.22+.
# 
