apiVersion: batch/v1
kind: Job
metadata:
  name: calcluate-pi
  namespace: test-deployments
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(20000)"]
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1"
          limits:
            memory: "2048Mi"
            cpu: "1"
      restartPolicy: Never
